// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5o-JQgNuChnfNy4uucCm-zPr5IciVt58',
    appId: '1:708261184819:web:88ba3ecf393667ab942a46',
    messagingSenderId: '708261184819',
    projectId: 'electronics-shop-fcaaf',
    authDomain: 'electronics-shop-fcaaf.firebaseapp.com',
    storageBucket: 'electronics-shop-fcaaf.firebasestorage.app',
    measurementId: 'G-PCE6G0KJ90',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-oxmgD6Xxhjky9thbOOI9glmqesoMhSU',
    appId: '1:708261184819:android:6ec90266c4aca74d942a46',
    messagingSenderId: '708261184819',
    projectId: 'electronics-shop-fcaaf',
    storageBucket: 'electronics-shop-fcaaf.firebasestorage.app',
  );
}
